# match test descriptions generated by LLM or written by humans based on focal methods to the target test cases.

import argparse
import json
import os
import instructor
from openai import OpenAI
from pydantic import BaseModel, Field, field_validator
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from configs import Configs
from dataset import Dataset
from tqdm import tqdm
from typing import Literal


# GPT_KEY = 'sk-bmjoWnVDWEHdcvAA8522CeE234Ca4a5189F4030c9632Fb46'
# GPT_BASE_URL = 'https://api.key77qiqi.com/v1'

# GPT_KEY = 'sk-xAKABRjShbq3JvfjM729GTe39bsJIyquiMCP0mJtbrx8nmCY'
GPT_KEY = 'sk-wxDb5OOqBynUaoMrzsGuiVMBdHJ7bIcsJ3nJSlmIJpaH1ywl'  # claude
GPT_BASE_URL = 'https://yunwu.ai/v1'

class DescMatchItem(BaseModel):
    idx: int = Field(..., ge=0, description="The index (1-based) of the best matching Test Description; 0 if no match is found.")
    matching_level: Literal["High", "Medium", "Low", "N/A"] = Field(..., description='"High", "Medium", or "Low" to indicate how closely the selected Test Description matches the Target Test Case; "N/A" if idx is 0.')
    num_candidates: int = Field(..., exclude=True, description="Total number of candidate test descriptions (for validation only).")
    
    @field_validator('idx')
    @classmethod
    def validate_idx_range(cls, v, info):
        num_candidates = info.context.get('num_candidates')
        if v < 0:
            raise ValueError('idx must be non-negative')
        if v > num_candidates:
            raise ValueError(f'idx must be between 0 and {num_candidates} (number of candidates), got {v}')
        return v
    
    @field_validator('matching_level')
    @classmethod
    def validate_matching_level_with_idx(cls, v, info):
        idx = info.data.get('idx')
        if idx == 0 and v != "N/A":
            raise ValueError('matching_level must be "N/A" when idx is 0')
        if idx != 0 and v == "N/A":
            raise ValueError('matching_level cannot be "N/A" when idx is non-zero')
        return v


class Judger:
    def __init__(self, llm_name: str):
        self.llm_name = llm_name

        custom_client = OpenAI(
                api_key=GPT_KEY, base_url=GPT_BASE_URL
            )
        self.client = instructor.from_openai(custom_client)
        
    def judge_match(self, focal_method: str, test_case: str, candidate_test_desc_list: list) -> tuple[str, int]:
        judgment_prompt = self.construct_prompt(focal_method, test_case, candidate_test_desc_list)

        judgment_prompt = f"{{% raw %}}{judgment_prompt}{{% endraw %}}"
        response = self.client.chat.completions.create(
            model=self.llm_name,
            response_model=DescMatchItem,
            messages=[
                {
                    "role": "user",
                    "content": judgment_prompt
                }
            ],
            temperature=0.1,
            max_tokens=10240,
            max_retries=5,
            validation_context={"num_candidates": len(candidate_test_desc_list)}
        )
        
        return response.matching_level, response.idx


    def construct_prompt(self, focal_method: str, test_case: str, candidate_test_desc_list: list) -> str:
        test_descriptions = '\n\n'.join([f'## Test Description (Idx-{idx+1})\n```\n{desc}\n```' for idx, desc in enumerate(candidate_test_desc_list)])

        prompt = f"""# Focal Method\n```\n{focal_method}\n```\n\n# Target Test Case\n```\n{test_case}\n```\n\n# Candidate Test Descriptions\n{test_descriptions}\n\n# Instruction\nAnalyze the Focal Method and the Target Test Case. Then review each Candidate Test Description and decide whether it describes essentially the same testing scenario as the Target Test Case (in terms of intent, inputs, preconditions, and expected behaviour).\nIf multiple Test Descriptions are similar, select the single best match.\nOutput:\n- Idx: the index (1-based) of the best matching Test Description if a match is found; otherwise output 0.\n- Matching Level: "High", "Medium", or "Low" to indicate how closely the selected Test Description matches the Target Test Case; output "N/A" if Idx is 0. Particularly, "High" must guarantee that the Preconditions and Expected Results are accurate and correct compared to the Target Test Case."""

        return prompt


def main():
    judger = Judger(llm_name)

    with open(configs.test_desc_from_fm_dataset_path, 'r') as f:
        raw_test_desc_data = json.load(f)
    focal_method_to_test_descs = {item['focal_method']: item['test_desc_list'] for item in raw_test_desc_data}
    
    save_path = configs.matched_test_desc_with_tc_dataset_path
    os.makedirs(os.path.dirname(save_path), exist_ok=True)

    # Load existing results if resuming
    if resume_generation_at > 0:
        with open(save_path, 'r') as f:
            matched_test_desc_dataset = json.load(f)
        print(f"Loaded {len(matched_test_desc_dataset)} existing results from {save_path}")
        assert len(matched_test_desc_dataset) == resume_generation_at, "The number of existing results does not match the resume index."
    else:
        matched_test_desc_dataset = []
    
    for target_pair_idx, each_target_pair in tqdm(enumerate(coverage_data), total=len(coverage_data), ncols=80, desc='Matching test desc'):
        if target_pair_idx < resume_generation_at:
            continue

        tar_fm = each_target_pair.focal_method
        tar_tc = each_target_pair.test_case
        candidate_test_descs = focal_method_to_test_descs.get(tar_fm)

        matching_level, matched_idx = judger.judge_match(tar_fm, tar_tc, candidate_test_descs)
        matched_test_desc_dataset.append({
            "coverage_idx": target_pair_idx,
            "focal_method": tar_fm,
            "test_case": tar_tc,
            "matching_level": matching_level,
            "matched_idx": matched_idx,
            "test_desc": candidate_test_descs[matched_idx - 1] if matching_level != "N/A" else ""
        })

        print(f"Coverage Idx: {target_pair_idx}\nFocal Method matched to Test Case with level: {matching_level}, matched_idx: {matched_idx}\nMatched Test Description:\n{candidate_test_descs[matched_idx - 1] if matching_level != 'N/A' else 'N/A'}\n\n\n")

        with open(save_path, 'w') as f:
            json.dump(matched_test_desc_dataset, f, indent=2)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--project_name', type=str, required=True, help='The name of the project.')
    parser.add_argument('--start_at', type=int, default=0, help='The index to resume generation at.')
    args = parser.parse_args()

    # llm_name = 'gpt-o1-mini'
    llm_name = 'claude-sonnet-4-5-20250929'
    # llm_name = 'claude-haiku-4-5-20251001'

    project_name = args.project_name
    resume_generation_at = args.start_at
    if resume_generation_at > 0:
        print(f"Resuming generation from index {resume_generation_at}")
        
    print(f'Project: {project_name}')

    print(f'\n\n\nProject: {project_name}')
    configs = Configs(project_name, llm_name='gpt-o1-mini')  # use "gpt-o1-mini" just for placeholder, the judger is specified by llm_name
    coverage_dataset = Dataset(configs)
    coverage_data = coverage_dataset.load_coverage_data_jacoco()
    configs.llm_name = llm_name

    main()